name: Wikize Refs Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - '!docs/**'

jobs:
  wikize-refs-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run wikize-refs on each file
        run: |
          set -x
          set +e
          exstat=0
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          echo $files
          pwd
          ls
          gorfo
          for file in $files; do
            v=$(python3 utils/wikize_refs.py -u "$file")
            echo "status is $v"
            if [[ $v -ne 0 ]]; then
                echo "$file needs wiki refs updated"
                exstat=1
            fi
          done
          exit $exstat
