name: Wikize Refs Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - '!docs/**'

jobs:
  wikize-refs-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run wikize-refs on each file
        run: |
          exstat=0
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          for file in $files; do
            utils/wikize-refs.py -u "$file"
            if [[ $? -ne 0 ]]; then
                echo "$file needs wiki refs updated"
                exstat=1
            fi
          done
          exit exstat
